services:
  backend:
    build:
      args:
        USER: ${USER:-appuser}
      context: ./stage-archive-backend
    depends_on:
      - postgres
    user: ${USER:-appuser}
    volumes:
      - ./static:/app/static
      - ./stage-archive-backend/:/app/
    command:  "python3 -m manage runserver 0:8000"
    ports:
      - 8000:8000

  frontend:
    image: giulios/flutter-ready:latest
    volumes:
      - frontend_code:/app/flutter_application
    ports:
      - 5000:5000
    entrypoint: "/bin/bash -l"
    tty: true
    # command: "sleep infinity"
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14-bullseye
    volumes:
      - pg_data:/var/lib/postgresql/data
  traefik:
    image: traefik:v2.6
    depends_on:
      - backend
      - frontend
    volumes:
      - ./traefik/:/traefik/:ro
    command:
      - "--configFile=/traefik/conf/static.yaml"
    ports:
      - "${LOCAL_HTTPS_PORT:-8443}:8443"
      - "${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
volumes:
  pg_data: {}
  staticfiles: {}
  frontend_code: 
    driver: local
    driver_opts:
      type: none
      device: ./stage-archive-frontend
      o: bind