services:
  backend:
    build:
      args:
        USER: ${USER:-appuser}
      context: ./stage-archive-backend
    depends_on:
      - postgres
    user: ${USER:-appuser}
    volumes:
      - ./stage-archive-backend:/app
      - ./static:/app/static
    command:  "python3 -m manage runserver 0:8000"
    ports:
      - 8000:8000

  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14-bullseye
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
  staticfiles: {}
